// Generated by scripts/generate-manifest.ts — do not edit by hand.
// The file path under commands/ defines the command path.

import type { CommandModule } from '@/shared/types/cli'

import * as on from '@/cli/commands/on'
import * as off from '@/cli/commands/off'
import * as root from '@/cli/commands/index'
import * as stop from '@/cli/commands/stop'
import * as sync from '@/cli/commands/sync'
import * as start from '@/cli/commands/start'
import * as state from '@/cli/commands/state'
import * as daemon_run from '@/cli/commands/daemon/run'
import * as preferences from '@/cli/commands/preferences'

export const commands: Record<string, CommandModule> = {
  '': root,
  'daemon run': daemon_run,
  'off': off,
  'on': on,
  'preferences': preferences,
  'start': start,
  'state': state,
  'stop': stop,
  'sync': sync,
}
