// Regenerates src/cli/manifest.ts from the commands tree. The file path
// defines the command path (commands/daemon/run.ts → "daemon run"), and the
// manifest keeps discovery static so bun build --compile can bundle it.
// Run after adding or removing a command file: bun scripts/generate-manifest.ts

import { readdirSync } from 'node:fs'
import { join, relative } from 'node:path'

const root = join(import.meta.dir, '..', 'src', 'cli', 'commands'),
  files: string[] = [],
  walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) walk(join(dir, entry.name))
      else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.test.ts')) {
        files.push(join(dir, entry.name))
      }
    }
  }

walk(root)

const entries = files
  .map((file) => {
    const rel = relative(root, file).replace(/\.ts$/, ''),
      command = rel === 'index' ? '' : rel.replaceAll('/', ' '),
      importName = rel === 'index' ? 'root' : rel.replaceAll('/', '_').replaceAll('-', '_')

    return { command, importName, path: `./commands/${rel}` }
  })
  .sort((a, b) => a.command.localeCompare(b.command))

const output = `
// Generated by scripts/generate-manifest.ts — do not edit by hand.
// The file path under commands/ defines the command path.

import type { CommandModule } from '@/shared/types/cli'

${entries.map((e) => `import * as ${e.importName} from '${e.path}'`).join('\n')}

export const commands: Record<string, CommandModule> = {
${entries.map((e) => `  '${e.command}': ${e.importName},`).join('\n')}
}
`

await Bun.write(join(import.meta.dir, '..', 'src', 'cli', 'manifest.ts'), output)

console.log(`manifest: ${entries.length} commands`)
